name: PyLEPR
channels:
    - conda-forge
    - defaults
dependencies:
    - python
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - jupyterlab    # Jupyter Lab environment
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - openpyxl
    - bs4
    - flake8
    - pep8
    - pip